#if !defined(AFX_RECORDSET_H__19EAED44_02F4_11D5_9FE4_C4B78D7E672E__INCLUDED_)
#define AFX_RECORDSET_H__19EAED44_02F4_11D5_9FE4_C4B78D7E672E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRecordset1 wrapper class

class CRecordset1 : public COleDispatchDriver
{
public:
	CRecordset1() {}		// Calls COleDispatchDriver default constructor
	CRecordset1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRecordset1(const CRecordset1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RECORDSET_H__19EAED44_02F4_11D5_9FE4_C4B78D7E672E__INCLUDED_)
