#if defined(FFT_CPP)
  #undef  MODULE
  #define MODULE   1
  #undef FFT_CPP
#elif defined(SPECTRUM_CPP)
  #undef  MODULE
  #define MODULE   2  
  #undef SPECTRUM_CPP
#elif defined(SPECTGRM_CPP)
  #undef  MODULE
  #define MODULE   3
  #undef SPECTGRM_CPP
#elif defined(DSPWINS_CPP)
  #undef  MODULE
  #define MODULE   4
  #undef DSPWINS_CPP
#elif defined(HPFLTR70_CPP)
  #undef  MODULE
  #define MODULE   5
  #undef  HPFLTR70_CPP  
#elif defined(FRAGMENT_CPP)
  #undef  MODULE
  #define MODULE   6
  #undef  FRAGMENT_CPP
#elif defined(WAVEWARP_CPP)
  #undef  MODULE
  #define MODULE   7
  #undef  WAVEWARP_CPP
#elif defined(LPC_CPP)
  #undef  MODULE
  #define MODULE   8  
  #undef  LPC_CPP
#elif defined(HISTGRAM_CPP)
  #undef  MODULE
  #define MODULE   9  
  #undef  HISTGRAM_CPP
#elif defined(CURVEFIT_CPP)
  #undef  MODULE
  #define MODULE   10
  #undef  CURVFIT_CPP  
#elif defined(PEAKPICK_CPP)
  #undef  MODULE
  #define MODULE   11 
  #undef  PEAKPICK_CPP
#elif defined(FORMANTS_CPP)
  #undef  MODULE
  #define MODULE   12 
  #undef  FORMANTS_CPP
#elif defined(COMPLEX_C)
  #undef  MODULE
  #define MODULE   13 
  #undef  COMPLEX_C
#elif defined(ZROOTS_C)
  #undef  MODULE
  #define MODULE   14 
  #undef  ZROOTS_C
  
#endif
