//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Sil.Sa.Riff {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class SaRiff80 {
        
        private FileReference fileReferenceField;
        
        private AudioEncodingInfo audioEncodingInfoField;
        
        private ReferenceInfo referenceInfoField;
        
        private LanguageInfo languageInfoField;
        
        private SpeakerInfo speakerInfoField;
        
        private Annotation annotationField;
        
        private MusicInfo musicInfoField;
        
        private DatabaseInfo databaseInfoField;
        
        private Preferences preferencesField;
        
        /// <remarks/>
        public FileReference FileReference {
            get {
                return this.fileReferenceField;
            }
            set {
                this.fileReferenceField = value;
            }
        }
        
        /// <remarks/>
        public AudioEncodingInfo AudioEncodingInfo {
            get {
                return this.audioEncodingInfoField;
            }
            set {
                this.audioEncodingInfoField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceInfo ReferenceInfo {
            get {
                return this.referenceInfoField;
            }
            set {
                this.referenceInfoField = value;
            }
        }
        
        /// <remarks/>
        public LanguageInfo LanguageInfo {
            get {
                return this.languageInfoField;
            }
            set {
                this.languageInfoField = value;
            }
        }
        
        /// <remarks/>
        public SpeakerInfo SpeakerInfo {
            get {
                return this.speakerInfoField;
            }
            set {
                this.speakerInfoField = value;
            }
        }
        
        /// <remarks/>
        public Annotation Annotation {
            get {
                return this.annotationField;
            }
            set {
                this.annotationField = value;
            }
        }
        
        /// <remarks/>
        public MusicInfo MusicInfo {
            get {
                return this.musicInfoField;
            }
            set {
                this.musicInfoField = value;
            }
        }
        
        /// <remarks/>
        public DatabaseInfo DatabaseInfo {
            get {
                return this.databaseInfoField;
            }
            set {
                this.databaseInfoField = value;
            }
        }
        
        /// <remarks/>
        public Preferences Preferences {
            get {
                return this.preferencesField;
            }
            set {
                this.preferencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class FileReference {
        
        private string nameField;
        
        private string driveVolumeField;
        
        private string driveTypeField;
        
        private string hashField;
        
        private string hashAlgField;
        
        private long lengthField;
        
        private System.DateTime modifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string DriveVolume {
            get {
                return this.driveVolumeField;
            }
            set {
                this.driveVolumeField = value;
            }
        }
        
        /// <remarks/>
        public string DriveType {
            get {
                return this.driveTypeField;
            }
            set {
                this.driveTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        public string HashAlg {
            get {
                return this.hashAlgField;
            }
            set {
                this.hashAlgField = value;
            }
        }
        
        /// <remarks/>
        public long Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class AudioEncodingInfo {
        
        private int channelsField;
        
        private int samplesPerSecondField;
        
        private int bandwidthField;
        
        private int bitsPerSampleField;
        
        private int effectiveBitsField;
        
        private long sampleCountField;
        
        private SignalRange signalRangeField;
        
        private SampleFlags sampleFlagsField;
        
        private RecordingInfo recordingInfoField;
        
        /// <remarks/>
        public int Channels {
            get {
                return this.channelsField;
            }
            set {
                this.channelsField = value;
            }
        }
        
        /// <remarks/>
        public int SamplesPerSecond {
            get {
                return this.samplesPerSecondField;
            }
            set {
                this.samplesPerSecondField = value;
            }
        }
        
        /// <remarks/>
        public int Bandwidth {
            get {
                return this.bandwidthField;
            }
            set {
                this.bandwidthField = value;
            }
        }
        
        /// <remarks/>
        public int BitsPerSample {
            get {
                return this.bitsPerSampleField;
            }
            set {
                this.bitsPerSampleField = value;
            }
        }
        
        /// <remarks/>
        public int EffectiveBits {
            get {
                return this.effectiveBitsField;
            }
            set {
                this.effectiveBitsField = value;
            }
        }
        
        /// <remarks/>
        public long SampleCount {
            get {
                return this.sampleCountField;
            }
            set {
                this.sampleCountField = value;
            }
        }
        
        /// <remarks/>
        public SignalRange SignalRange {
            get {
                return this.signalRangeField;
            }
            set {
                this.signalRangeField = value;
            }
        }
        
        /// <remarks/>
        public SampleFlags SampleFlags {
            get {
                return this.sampleFlagsField;
            }
            set {
                this.sampleFlagsField = value;
            }
        }
        
        /// <remarks/>
        public RecordingInfo RecordingInfo {
            get {
                return this.recordingInfoField;
            }
            set {
                this.recordingInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class SignalRange {
        
        private int maxField;
        
        private int minField;
        
        /// <remarks/>
        public int Max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        public int Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class SampleFlags {
        
        private bool sampleWordSizeConvertedField;
        
        private bool sampleRateConvertedField;
        
        private bool sampleDataCompressedField;
        
        private bool sampleDataLossyField;
        
        /// <remarks/>
        public bool SampleWordSizeConverted {
            get {
                return this.sampleWordSizeConvertedField;
            }
            set {
                this.sampleWordSizeConvertedField = value;
            }
        }
        
        /// <remarks/>
        public bool SampleRateConverted {
            get {
                return this.sampleRateConvertedField;
            }
            set {
                this.sampleRateConvertedField = value;
            }
        }
        
        /// <remarks/>
        public bool SampleDataCompressed {
            get {
                return this.sampleDataCompressedField;
            }
            set {
                this.sampleDataCompressedField = value;
            }
        }
        
        /// <remarks/>
        public bool SampleDataLossy {
            get {
                return this.sampleDataLossyField;
            }
            set {
                this.sampleDataLossyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class RecordingInfo {
        
        private HighpassFilter highpassFilterField;
        
        private RecordingFormat recordingFormatField;
        
        private int bandwidthField;
        
        private System.DateTime recordingTimeField;
        
        private int bitsPerSampleField;
        
        /// <remarks/>
        public HighpassFilter HighpassFilter {
            get {
                return this.highpassFilterField;
            }
            set {
                this.highpassFilterField = value;
            }
        }
        
        /// <remarks/>
        public RecordingFormat RecordingFormat {
            get {
                return this.recordingFormatField;
            }
            set {
                this.recordingFormatField = value;
            }
        }
        
        /// <remarks/>
        public int Bandwidth {
            get {
                return this.bandwidthField;
            }
            set {
                this.bandwidthField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RecordingTime {
            get {
                return this.recordingTimeField;
            }
            set {
                this.recordingTimeField = value;
            }
        }
        
        /// <remarks/>
        public int BitsPerSample {
            get {
                return this.bitsPerSampleField;
            }
            set {
                this.bitsPerSampleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public enum HighpassFilter {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        HP70Hz,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public enum RecordingFormat {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        UTT,
        
        /// <remarks/>
        WAV,
        
        /// <remarks/>
        MAC,
        
        /// <remarks/>
        TIMIT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class ReferenceInfo {
        
        private string descriptionField;
        
        private string freeTranslationField;
        
        private string noteBookField;
        
        private string transcriberField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string FreeTranslation {
            get {
                return this.freeTranslationField;
            }
            set {
                this.freeTranslationField = value;
            }
        }
        
        /// <remarks/>
        public string NoteBook {
            get {
                return this.noteBookField;
            }
            set {
                this.noteBookField = value;
            }
        }
        
        /// <remarks/>
        public string Transcriber {
            get {
                return this.transcriberField;
            }
            set {
                this.transcriberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class LanguageInfo {
        
        private string ethnologueIDField;
        
        private string familyField;
        
        private string languageField;
        
        private string dialectField;
        
        private string countryField;
        
        private string regionField;
        
        /// <remarks/>
        public string EthnologueID {
            get {
                return this.ethnologueIDField;
            }
            set {
                this.ethnologueIDField = value;
            }
        }
        
        /// <remarks/>
        public string Family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string Dialect {
            get {
                return this.dialectField;
            }
            set {
                this.dialectField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class SpeakerInfo {
        
        private Age ageField;
        
        private bool ageFieldSpecified;
        
        private Gender genderField;
        
        private bool genderFieldSpecified;
        
        private string speakerNameField;
        
        /// <remarks/>
        public Age Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AgeSpecified {
            get {
                return this.ageFieldSpecified;
            }
            set {
                this.ageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SpeakerName {
            get {
                return this.speakerNameField;
            }
            set {
                this.speakerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public enum Age {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Adult,
        
        /// <remarks/>
        Child,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public enum Gender {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Female,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class Annotation {
        
        private Segment[] phonemicField;
        
        private Segment[] phoneticField;
        
        private Segment[] toneField;
        
        private Segment[] orthographicField;
        
        private Segment[] glossField;
        
        private Segment[] partOfSpeechField;
        
        private Segment[] referenceField;
        
        private Segment[] phrase1Field;
        
        private Segment[] phrase2Field;
        
        private Segment[] phrase3Field;
        
        private Segment[] phrase4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Phonemic {
            get {
                return this.phonemicField;
            }
            set {
                this.phonemicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Phonetic {
            get {
                return this.phoneticField;
            }
            set {
                this.phoneticField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Tone {
            get {
                return this.toneField;
            }
            set {
                this.toneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Orthographic {
            get {
                return this.orthographicField;
            }
            set {
                this.orthographicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Gloss {
            get {
                return this.glossField;
            }
            set {
                this.glossField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] PartOfSpeech {
            get {
                return this.partOfSpeechField;
            }
            set {
                this.partOfSpeechField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Phrase1 {
            get {
                return this.phrase1Field;
            }
            set {
                this.phrase1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Phrase2 {
            get {
                return this.phrase2Field;
            }
            set {
                this.phrase2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Phrase3 {
            get {
                return this.phrase3Field;
            }
            set {
                this.phrase3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable=false)]
        public Segment[] Phrase4 {
            get {
                return this.phrase4Field;
            }
            set {
                this.phrase4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class Segment {
        
        private string contentField;
        
        private double beginField;
        
        private double endField;
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class DatabaseInfo {
        
        private string applicationNameField;
        
        private string applicationTitleField;
        
        private Registration[] registrationField;
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationTitle {
            get {
                return this.applicationTitleField;
            }
            set {
                this.applicationTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registration")]
        public Registration[] Registration {
            get {
                return this.registrationField;
            }
            set {
                this.registrationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class Registration {
        
        private string databaseNameField;
        
        private System.DateTime registrationTimeStampField;
        
        private bool registrationTimeStampFieldSpecified;
        
        private string[] keyField;
        
        /// <remarks/>
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegistrationTimeStamp {
            get {
                return this.registrationTimeStampField;
            }
            set {
                this.registrationTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistrationTimeStampSpecified {
            get {
                return this.registrationTimeStampFieldSpecified;
            }
            set {
                this.registrationTimeStampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Key")]
        public string[] Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class MusicInfo {
        
        private string musicScoreField;
        
        /// <remarks/>
        public string MusicScore {
            get {
                return this.musicScoreField;
            }
            set {
                this.musicScoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class Preferences {
        
        private Fonts fontsField;
        
        private GrapplCustomPitch grapplCustomPitchField;
        
        /// <remarks/>
        public Fonts Fonts {
            get {
                return this.fontsField;
            }
            set {
                this.fontsField = value;
            }
        }
        
        /// <remarks/>
        public GrapplCustomPitch GrapplCustomPitch {
            get {
                return this.grapplCustomPitchField;
            }
            set {
                this.grapplCustomPitchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class Fonts {
        
        private string phonemicField;
        
        private string phoneticField;
        
        private string toneField;
        
        private string orthographicField;
        
        private string glossField;
        
        private string partOfSpeechField;
        
        private string referenceField;
        
        private string phrase1Field;
        
        private string phrase2Field;
        
        private string phrase3Field;
        
        private string phrase4Field;
        
        /// <remarks/>
        public string Phonemic {
            get {
                return this.phonemicField;
            }
            set {
                this.phonemicField = value;
            }
        }
        
        /// <remarks/>
        public string Phonetic {
            get {
                return this.phoneticField;
            }
            set {
                this.phoneticField = value;
            }
        }
        
        /// <remarks/>
        public string Tone {
            get {
                return this.toneField;
            }
            set {
                this.toneField = value;
            }
        }
        
        /// <remarks/>
        public string Orthographic {
            get {
                return this.orthographicField;
            }
            set {
                this.orthographicField = value;
            }
        }
        
        /// <remarks/>
        public string Gloss {
            get {
                return this.glossField;
            }
            set {
                this.glossField = value;
            }
        }
        
        /// <remarks/>
        public string PartOfSpeech {
            get {
                return this.partOfSpeechField;
            }
            set {
                this.partOfSpeechField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string Phrase1 {
            get {
                return this.phrase1Field;
            }
            set {
                this.phrase1Field = value;
            }
        }
        
        /// <remarks/>
        public string Phrase2 {
            get {
                return this.phrase2Field;
            }
            set {
                this.phrase2Field = value;
            }
        }
        
        /// <remarks/>
        public string Phrase3 {
            get {
                return this.phrase3Field;
            }
            set {
                this.phrase3Field = value;
            }
        }
        
        /// <remarks/>
        public string Phrase4 {
            get {
                return this.phrase4Field;
            }
            set {
                this.phrase4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sil.org/computing/schemas/asap/sa/SaDoc-RIFF8.0/0.0", IsNullable=false)]
    public partial class GrapplCustomPitch {
        
        private int calcFreqLowField;
        
        private int calcFreqHighField;
        
        private int calcVoicingThdField;
        
        private int calcPercntChngField;
        
        private int calcGrpSizeField;
        
        private int calcIntrpGapField;
        
        /// <remarks/>
        public int CalcFreqLow {
            get {
                return this.calcFreqLowField;
            }
            set {
                this.calcFreqLowField = value;
            }
        }
        
        /// <remarks/>
        public int CalcFreqHigh {
            get {
                return this.calcFreqHighField;
            }
            set {
                this.calcFreqHighField = value;
            }
        }
        
        /// <remarks/>
        public int CalcVoicingThd {
            get {
                return this.calcVoicingThdField;
            }
            set {
                this.calcVoicingThdField = value;
            }
        }
        
        /// <remarks/>
        public int CalcPercntChng {
            get {
                return this.calcPercntChngField;
            }
            set {
                this.calcPercntChngField = value;
            }
        }
        
        /// <remarks/>
        public int CalcGrpSize {
            get {
                return this.calcGrpSizeField;
            }
            set {
                this.calcGrpSizeField = value;
            }
        }
        
        /// <remarks/>
        public int CalcIntrpGap {
            get {
                return this.calcIntrpGapField;
            }
            set {
                this.calcIntrpGapField = value;
            }
        }
    }
}
